// Datos de demostración para modo offline
const DEMO_DATA = {
    profiles: [
        {
            id: 1,
            name: "Sofia Luna",
            category: "photography",
            tags: ["Retrato", "Fashion", "Artístico"],
            experience: "3 años",
            rating: 4.8,
            avatar: "👩🦰",
            description: "Especialista en fotografía artística y retratos elegantes con más de 3 años de experiencia.",
            portfolio: ["Sesión fashion 2024", "Retratos corporativos", "Arte conceptual"],
            instagram: "@sofialuna",
            location: "Madrid, España",
            age: 24
        },
        {
            id: 2,
            name: "Isabella Rose",
            category: "video",
            tags: ["Contenido", "Edición", "Streaming"],
            experience: "2 años",
            rating: 4.9,
            avatar: "👩🦱",
            description: "Creadora de contenido audiovisual premium especializada en producción de alta calidad.",
            portfolio: ["Videos promocionales", "Contenido para redes", "Live streaming"],
            instagram: "@isabellarose",
            location: "Barcelona, España",
            age: 22
        },
        {
            id: 3,
            name: "Valentina Star",
            category: "modeling",
            tags: ["Runway", "Editorial", "Commercial"],
            experience: "4 años",
            rating: 4.7,
            avatar: "👩🦳",
            description: "Modelo profesional con experiencia internacional en pasarelas y campañas publicitarias.",
            portfolio: ["Pasarelas internacionales", "Campañas publicitarias", "Editorial de moda"],
            instagram: "@valentinastar",
            location: "Valencia, España",
            age: 26
        },
        {
            id: 4,
            name: "Camila Dreams",
            category: "streaming",
            tags: ["Gaming", "Chat", "Entretenimiento"],
            experience: "1 año",
            rating: 4.6,
            avatar: "👩",
            description: "Streamer carismática especializada en entretenimiento interactivo y gaming.",
            portfolio: ["Streams de gaming", "Shows interactivos", "Colaboraciones"],
            instagram: "@camiladreams",
            location: "Sevilla, España",
            age: 20
        },
        {
            id: 5,
            name: "Andrea Luxe",
            category: "photography",
            tags: ["Boudoir", "Glamour", "Artístico"],
            experience: "5 años",
            rating: 4.9,
            avatar: "👩🦲",
            description: "Fotógrafa especializada en sesiones de lujo y fotografía glamour de alto nivel.",
            portfolio: ["Sesiones boudoir", "Fotografía glamour", "Retratos íntimos"],
            instagram: "@andrealuxe",
            location: "Bilbao, España",
            age: 28
        },
        {
            id: 6,
            name: "Natalia Vogue",
            category: "video",
            tags: ["Fashion", "Beauty", "Lifestyle"],
            experience: "3 años",
            rating: 4.8,
            avatar: "🧑🦰",
            description: "Productora de contenido fashion y lifestyle con enfoque en tendencias actuales.",
            portfolio: ["Videos de moda", "Tutoriales beauty", "Vlogs lifestyle"],
            instagram: "@nataliavogue",
            location: "Málaga, España",
            age: 25
        },
        {
            id: 7,
            name: "Luna Starlight",
            category: "streaming",
            tags: ["ASMR", "Chat", "Música"],
            experience: "2 años",
            rating: 4.7,
            avatar: "👩🦱",
            description: "Creadora de contenido ASMR y streams musicales con comunidad activa.",
            portfolio: ["ASMR sessions", "Música en vivo", "Charlas nocturnas"],
            instagram: "@lunastarlight",
            location: "Zaragoza, España",
            age: 23
        },
        {
            id: 8,
            name: "Victoria Elite",
            category: "modeling",
            tags: ["Fitness", "Swimwear", "Lifestyle"],
            experience: "4 años",
            rating: 4.9,
            avatar: "👩🦳",
            description: "Modelo fitness y lifestyle con presencia en marcas deportivas internacionales.",
            portfolio: ["Campañas fitness", "Swimwear shoots", "Lifestyle content"],
            instagram: "@victoriaelite",
            location: "Alicante, España",
            age: 27
        },
        {
            id: 9,
            name: "Daniela Charm",
            category: "photography",
            tags: ["Editorial", "Conceptual", "Fine Art"],
            experience: "6 años",
            rating: 5.0,
            avatar: "👩",
            description: "Artista visual especializada en fotografía conceptual y editorial de vanguardia.",
            portfolio: ["Editorial magazines", "Arte conceptual", "Exposiciones"],
            instagram: "@danielacharm",
            location: "Granada, España",
            age: 29
        }
    ],

    candidates: [
        {
            id: 101,
            name: "María García",
            email: "maria.garcia@email.com",
            age: 23,
            category: "photography",
            status: "new",
            rating: 0,
            date: new Date('2024-01-20'),
            avatar: "👩🦰",
            description: "Fotógrafa emergente con pasión por el retrato artístico",
            experience: "1-2 años",
            location: "Madrid, España",
            availability: "part-time",
            skills: "Photoshop, Lightroom, Fotografía analógica",
            instagram: "@mariagarcia_photo",
            tiktok: "",
            notes: ""
        },
        {
            id: 102,
            name: "Laura Martínez",
            email: "laura.martinez@email.com",
            age: 25,
            category: "video",
            status: "review",
            rating: 4,
            date: new Date('2024-01-19'),
            avatar: "👩🦱",
            description: "Editora de video con experiencia en contenido para redes sociales",
            experience: "2-5 años",
            location: "Barcelona, España",
            availability: "full-time",
            skills: "Premiere Pro, After Effects, DaVinci Resolve",
            instagram: "@lauramartinez",
            tiktok: "@lauramartinez",
            notes: "Portfolio muy completo, excelente edición"
        },
        {
            id: 103,
            name: "Carmen López",
            email: "carmen.lopez@email.com",
            age: 21,
            category: "streaming",
            status: "new",
            rating: 0,
            date: new Date('2024-01-20'),
            avatar: "👩",
            description: "Streamer con comunidad activa en Twitch",
            experience: "0-1 año",
            location: "Valencia, España",
            availability: "flexible",
            skills: "OBS, Streaming, Community management",
            instagram: "@carmenlopez",
            tiktok: "@carmenlopez",
            notes: ""
        },
        {
            id: 104,
            name: "Ana Rodríguez",
            email: "ana.rodriguez@email.com",
            age: 26,
            category: "modeling",
            status: "approved",
            rating: 5,
            date: new Date('2024-01-18'),
            avatar: "👩🦳",
            description: "Modelo profesional con experiencia en pasarelas",
            experience: "5+ años",
            location: "Sevilla, España",
            availability: "full-time",
            skills: "Runway, Editorial, Commercial modeling",
            instagram: "@anarodriguez",
            tiktok: "",
            notes: "Perfil excepcional, aprobada inmediatamente"
        },
        {
            id: 105,
            name: "Elena Fernández",
            email: "elena.fernandez@email.com",
            age: 24,
            category: "photography",
            status: "review",
            rating: 3,
            date: new Date('2024-01-19'),
            avatar: "👩🦲",
            description: "Fotógrafa de moda y lifestyle",
            experience: "2-5 años",
            location: "Bilbao, España",
            availability: "part-time",
            skills: "Fashion photography, Retouching, Styling",
            instagram: "@elenafernandez",
            tiktok: "",
            notes: "Buen portfolio, pendiente de entrevista"
        },
        {
            id: 106,
            name: "Paula Sánchez",
            email: "paula.sanchez@email.com",
            age: 22,
            category: "video",
            status: "new",
            rating: 0,
            date: new Date('2024-01-21'),
            avatar: "🧑🦰",
            description: "Creadora de contenido para YouTube e Instagram",
            experience: "1-2 años",
            location: "Málaga, España",
            availability: "flexible",
            skills: "Video editing, Content creation, Social media",
            instagram: "@paulasanchez",
            tiktok: "@paulasanchez",
            notes: ""
        },
        {
            id: 107,
            name: "Lucía Torres",
            email: "lucia.torres@email.com",
            age: 27,
            category: "modeling",
            status: "rejected",
            rating: 2,
            date: new Date('2024-01-17'),
            avatar: "👩🦱",
            description: "Modelo freelance",
            experience: "2-5 años",
            location: "Zaragoza, España",
            availability: "weekends",
            skills: "Commercial modeling, Social media",
            instagram: "@luciatorres",
            tiktok: "",
            notes: "No cumple con los requisitos de experiencia"
        },
        {
            id: 108,
            name: "Sara Jiménez",
            email: "sara.jimenez@email.com",
            age: 25,
            category: "streaming",
            status: "review",
            rating: 4,
            date: new Date('2024-01-19'),
            avatar: "👩",
            description: "Streamer de contenido variado y gaming",
            experience: "1-2 años",
            location: "Alicante, España",
            availability: "full-time",
            skills: "Streaming, Gaming, Community engagement",
            instagram: "@sarajimenez",
            tiktok: "@sarajimenez",
            notes: "Buena presencia, comunidad activa"
        }
    ]
};
